### ISSUE TITLE
require() of ES Module not supported

### ISSUE THREAD

**Issue by HXM4Tech** [Assassin-1234/discord-wrapped#10]
The following error occurs when running `node .` with Node.js v19.7.0 on linux:

```js
/home/ks/discord-wrapped/src/animations/wrap.js:6
const editly = require('editly');
               ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/ks/discord-wrapped/node_modules/editly/index.js from /home/ks/discord-wrapped/src/animations/wrap.js not supported.
Instead change the require of index.js in /home/ks/discord-wrapped/src/animations/wrap.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/ks/discord-wrapped/src/animations/wrap.js:6:16)
    at /home/ks/discord-wrapped/index.js:3:15
    at Object.<anonymous> (/home/ks/discord-wrapped/index.js:5:3) {
  code: 'ERR_REQUIRE_ESM'
}
```

After changing `src/animations/wrap.js`
```diff
- const editly = require('editly');
+ const editly = import('editly');
```
another TypeError is thrown:
```js

Processed 100% of Analytics data (708670779 / 708850519)...
Finished creating 1st frame
Finished creating 2nd frame
Finished creating 3rd frame
Finished creating 4th frame
Finished creating 5th frame
Finished creating 6th frame
Finished creating 7th frame
/home/ks/discord-wrapped/src/animations/wrap.js:393
        editly({
        ^

TypeError: editly is not a function
    at module.exports (/home/ks/discord-wrapped/src/animations/wrap.js:393:2)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/ks/discord-wrapped/index.js:4:2
```

**Comment by GGORG0** [comment]
Possible causes:
 - https://github.com/sindresorhus/file-type/releases/tag/v17.0.0
 - https://github.com/mifi/editly/releases/tag/v0.13.0
 - https://github.com/Assassin-1234/discord-wrapped/commit/ac8597c525de91e0e34ec870ef190cf5aeebdf44

Don't just blindly update to a new major version with breaking changes!

**Comment by Assassin-1234** [comment]
my bad, looks like we updated to what I thought was a minor version of editly to fix a security vulnerability. Reverted back in https://github.com/Assassin-1234/discord-wrapped/commit/3c220edc5ca0fb606b664a5ec78efe0756bec565.

**Comment by HXM4Tech** [comment]
It looks like the same error still occurs and also FFmpeg is no longer being found in `/usr/bin/`
3c220ed does not actually change `const editly = require('editly')` which causes the problem.

**Comment by HXM4Tech** [comment]
It seems as changing `package.json`
```diff
- "editly": "^0.14.2",
+ "editly": "^0.12",
```
fixes the problem, but FFmpeg still isn't seen.

**Comment by HXM4Tech** [comment]
#11
