### ISSUE TITLE
website not loading

### ISSUE THREAD

**Issue by Pitchstep** [Assassin-1234/discord-wrapped#15]
![image](https://github.com/Assassin-1234/discord-wrapped/assets/109386708/79c93814-6810-453c-8065-7332a2582467)

**Comment by v11nc33alt** [comment]
> ![image](https://github.com/Assassin-1234/discord-wrapped/assets/109386708/79c93814-6810-453c-8065-7332a2582467)
> 
> 

Bro had no more cash to pay the domain name 💀💀💀🫡

**Comment by GGLVXD** [comment]
Wth its ssl not that domain is expired

**Comment by Assassin-1234** [comment]
looks like I messed up the configuration of the website while making a few changes to my VPS, will be up and running soon

**Comment by Iliannnn** [comment]
The site is back online. You might need to clear your cache for it to work.

Let us know if everything is working fine now!
