### ISSUE TITLE
[Bug] Discord wrapped redirecting me to https://zyztem.dev/ instead of discord wrapped

### ISSUE THREAD

**Issue by BubblyBreadysi** [Assassin-1234/discord-wrapped#17]
### **Describe the issue**
When clicking the https://discordwrapped.com link it redirects me to https://zyztem.dev/

### **To Reproduce**
Github -> click on https://discordwrapped.com 

### **Expected behavior**
Should show me the discord wrapped website instead of https://zyztem.dev/

### **Documentation**
Video example is shown below 

https://github.com/user-attachments/assets/12fae577-7eb3-4920-92de-59e5377512a8

**Comment by Iliannnn** [comment]
The site is back online and I fixed this. You might need to clear your cache for it to work.

Let us know if everything is working fine now!

**Comment by BubblyBreadysi** [comment]
Hey, 

Thank you for putting the site back online. However I am having another issue. 

### Describe the issue
When uploading the package it keeps coming up with this error. I have cleaned my cache. 

### To Reproduce
https://discordwrapped.com/ -> Upload discord data package

### Expected behavior
Should upload successfully and show the discord wrapped and not show error at the unzipping data package part

### Documentation
Video example is shown below

https://github.com/user-attachments/assets/973b3814-a3cd-4deb-9b8e-110950bddaeb

**Comment by bubblycatbread** [comment]
> The site is back online and I fixed this. You might need to clear your cache for it to work.
> 
> Let us know if everything is working fine now!

Hey, 

Thank you for putting the site back online. However I am having another issue. I have made a new issue about it. Thank you for putting the site online though. I appreciate it :)
